26 as a user i want to validate if metadata is hip 412 compliant
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #14
Opened 2024-02-21 11:40 UTC by michalrozekariane

2024-02-21 14:54 UTC, BartoszSolkaArianelabs requested changes

2024-02-21 14:54 UTC, BartoszSolkaArianelabs commented on src/hip412-validator/index.ts
> +    let allFilesValid = true;
this can be removed

2024-02-21 14:54 UTC, BartoszSolkaArianelabs commented on src/hip412-validator/index.ts
> +    return { isValid: allFilesValid, errors };
`allFilesValid` can be replaced with `errors.length`?

2024-02-21 17:12 UTC, michalrozekariane commented on src/api/mirror-node.ts
> +  let allNFTs: NFTDetails[] = [];
No because this function is changing the values for them with every iteraton

2024-02-21 17:15 UTC, michalrozekariane commented on src/api/mirror-node.ts
> +export async function getSingleNFTMetadata(network: NetworkName, tokenId: string, serialNumber: number): Promise<NFTDetails> {
done

2024-02-21 17:23 UTC, michalrozekariane commented on src/helpers/uri-decoder.ts
> +    };
done

2024-02-21 17:24 UTC, michalrozekariane commented on src/helpers/uri-decoder.ts
> +import { NFTDetails, DecodedMetadata } from '../types/nfts.module';
added

2024-02-21 17:28 UTC, michalrozekariane commented on src/hip412-validator/index.ts
> +    let allFilesValid = true;
done

2024-02-21 17:29 UTC, michalrozekariane commented on src/hip412-validator/index.ts
> +    return { isValid: allFilesValid, errors };
done

2024-02-22 08:14 UTC, BartoszSolkaArianelabs commented on src/api/mirror-node.ts
> +  let allNFTs: NFTDetails[] = [];
another way to do it would be
```
  const allNFTs: NFTDetails[] = [];
```

and

```
      allNFTs.push(...response.data.nfts);
```

2024-02-22 08:37 UTC, BartoszSolkaArianelabs approved these changes

2024-02-22 08:56 UTC, michalrozekariane commented on src/api/mirror-node.ts
> +  let allNFTs: NFTDetails[] = [];
done

2024-02-22 09:49 UTC, michalrozekariane commented on src/hip412-validator/index.ts
> +        // Sorts the file names numerically ensuring that files are ordered naturally (e.g., '1', '2', '10' instead of '1', '10', '2').
done

2024-02-22 09:58 UTC, StanislawMazowieckiAriane approved these changes

2024-02-22 11:38 UTC, se7enarianelabs approved these changes

2024-02-22 11:39 UTC, merged