Feat: Add changing default values to risk calculation. Add tests
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #15
Opened 2024-02-21 12:12 UTC by StanislawMazowieckiAriane

2024-02-21 15:06 UTC, se7enarianelabs requested changes

2024-02-21 15:06 UTC, se7enarianelabs commented on src/risk/index.ts
> +
In my opinion, the risk functions should be stateless. This means you should be able to provide your weights and riskLevels through optional parameters. If the parameters are omitted, the function should use default values.

2024-02-21 15:06 UTC, se7enarianelabs commented on src/risk/index.ts
>      network === 'mainnet'
The SDK supports previewnet and localnodes as well

2024-02-21 16:44 UTC, StanislawMazowieckiAriane commented on src/risk/index.ts
> +
But it is. It has default values. Only if the user want to customize them, he uses one of the update functions

2024-02-21 16:53 UTC, StanislawMazowieckiAriane commented on src/risk/index.ts
>      network === 'mainnet'
Done

2024-02-22 09:47 UTC, StanislawMazowieckiAriane commented on src/risk/index.ts
> +
Done

2024-02-22 09:52 UTC, StanislawMazowieckiAriane commented on src/risk/index.ts
> +      throw new Error('Invalid network');
Done

2024-02-22 11:43 UTC, se7enarianelabs approved these changes

2024-02-22 11:46 UTC, michalrozekariane approved these changes

2024-02-22 12:06 UTC, merged