Feat: Update rarity functions. Add tests. Add on chain function
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #25
Opened 2024-02-26 08:59 UTC by StanislawMazowieckiAriane

2024-02-27 11:41 UTC, BartoszSolkaArianelabs approved these changes

2024-02-27 11:52 UTC, michalrozekariane requested changes

2024-02-27 11:52 UTC, michalrozekariane commented on src/rarity/index.ts
> +      if (!attributeConfigObject) throw new Error(`Attribute ${NFTAttribute.trait_type} not found in attributes map`);
pls add this error to dictionary

2024-02-27 11:52 UTC, michalrozekariane commented on src/rarity/index.ts
> +      throw new Error(`Attributes not found in file ${file.filename}. Please ensure that your metadata file is valid.`);
pls add this error to dictionary

2024-02-27 11:52 UTC, michalrozekariane commented on src/rarity/index.ts
> +      throw new Error(`Attributes not found in object ${JSON.stringify(metadata)}. Please ensure that your metadata file is valid.`);
pls use error from dictionary

2024-02-27 11:52 UTC, michalrozekariane commented on src/rarity/index.ts
> +      if (!attributeConfigObject) throw new Error(`Attribute ${NFTAttribute.trait_type} not found in attributes map`);
pls use error from dictionary

2024-02-28 09:24 UTC, se7enarianelabs approved these changes

2024-02-29 09:01 UTC, StanislawMazowieckiAriane commented on src/rarity/index.ts
> +      throw new Error(`Attributes not found in object ${JSON.stringify(metadata)}. Please ensure that your metadata file is valid.`);
Done

2024-02-29 09:01 UTC, StanislawMazowieckiAriane commented on src/rarity/index.ts
> +      if (!attributeConfigObject) throw new Error(`Attribute ${NFTAttribute.trait_type} not found in attributes map`);
Done

2024-02-29 09:01 UTC, StanislawMazowieckiAriane commented on src/rarity/index.ts
> +      if (!attributeConfigObject) throw new Error(`Attribute ${NFTAttribute.trait_type} not found in attributes map`);
Done

2024-02-29 09:08 UTC, michalrozekariane approved these changes

2024-02-29 09:12 UTC, merged