28 global way to close hedera client in end to end tests
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #33
Opened 2024-02-26 13:46 UTC by michalrozekariane

Fixes #28

2024-02-27 11:32 UTC, BartoszSolkaArianelabs approved these changes

2024-02-28 09:21 UTC, se7enarianelabs requested changes

2024-02-28 09:21 UTC, se7enarianelabs commented on src/test/config/afterEnvSetup.ts
> +});
Strange file name and missing hedera license header

2024-02-28 09:21 UTC, se7enarianelabs commented on src/test/e2e/storage-provider-e2e.test.ts
> +import { awsSecretKey, awsAccessKey, nftStorageApiKey, pinataApiKey, pinataJwtKey, pinataSecretApiKey, nftSDK } from './e2e-consts';
why did you add the nftSDK import?

2024-02-28 12:29 UTC, michalrozekariane commented on src/test/config/afterEnvSetup.ts
> +});
done

2024-02-28 13:47 UTC, se7enarianelabs approved these changes

2024-02-28 13:49 UTC, merged