55-documentation-2
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #58
Opened 2024-03-21 09:07 UTC by michalrozekariane

2024-03-21 17:25 UTC, StanislawMazowieckiAriane commented on README.md
> +- Array of errors
Maby ad and example of how those errors look

2024-03-21 17:25 UTC, StanislawMazowieckiAriane commented on README.md
> +  - `fileName`: The name of the file that encountered validation errors, helping to identify the source of the issue.
space

2024-03-21 17:25 UTC, StanislawMazowieckiAriane commented on README.md
> +- `errors`: An array of MetadataError objects, each corresponding to a file that failed validation. Each MetadataError object can include:
Could you tell what MetadataError is? Maby show it somewhere

2024-03-21 17:25 UTC, StanislawMazowieckiAriane commented on README.md
> +- setName(name: string): 'Sets the name of the NFT',
Is everything here required?

2024-03-21 17:25 UTC, StanislawMazowieckiAriane commented on README.md
> +console.log(builder.metadata); // The constructed metadata object
I would write it like this: 
const { metadata, validationResponse } = new Hip412MetadataBuilder()
.setName...

instead those console logs

2024-03-22 08:57 UTC, michalrozekariane commented on README.md
> +  - `fileName`: The name of the file that encountered validation errors, helping to identify the source of the issue.
`fileName` and `general` fields are nested inside `errors` that's why I added those spaces

2024-03-22 09:52 UTC, michalrozekariane commented on README.md
> +- Array of errors
done

2024-03-22 09:52 UTC, michalrozekariane commented on README.md
> +- `errors`: An array of MetadataError objects, each corresponding to a file that failed validation. Each MetadataError object can include:
done

2024-03-22 09:54 UTC, michalrozekariane commented on README.md
> +- setName(name: string): 'Sets the name of the NFT',
done

2024-03-22 10:07 UTC, michalrozekariane commented on README.md
> +console.log(builder.metadata); // The constructed metadata object
done

2024-03-22 10:34 UTC, StanislawMazowieckiAriane approved these changes

2024-03-25 08:55 UTC, BartoszSolkaArianelabs requested changes

2024-03-25 08:55 UTC, BartoszSolkaArianelabs commented on README.md
> +<strong>Important!</strong> The first two lines in the csv file are headers and they are skipped.
Let's mention where users can see the example of a valid csv format

2024-03-25 11:39 UTC, michalrozekariane commented on README.md
> +Each of NFtSDK function are methods in class `NFTSDK` which is a wrapper around the Hedera NFT API. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
done

2024-03-25 11:39 UTC, michalrozekariane commented on README.md
> +5. **Trait occurrence calculation:**
done

2024-03-25 11:45 UTC, michalrozekariane commented on README.md
> +<strong>Important!</strong> The first two lines in the csv file are headers and they are skipped.
done

2024-03-25 11:45 UTC, BartoszSolkaArianelabs approved these changes

2024-03-25 11:50 UTC, merged