55 documentation
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #59
Opened 2024-03-21 09:31 UTC by StanislawMazowieckiAriane

2024-03-21 10:52 UTC, BartoszSolkaArianelabs requested changes

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +Each of NFtSDK function are methods in class `NFTSDK` which is a wrapper around the Hedera NFT API. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
NFtSDK typo

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +Create new instance of `NFTSDK` class by passing the operator account ID, operator private key, and network to the constructor.
Let's use the `HederaNFTSDK` name

Create new instance of `HederaNFTSDK` ...

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +### Parameters
This paragraph should be after `## NFT SDK Create Collection`

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +```
maybe let's remove the installation step from these examples and just leave it in the `## NFT SDK methods` section

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +Method return number which is the estimated cost of creating a new NFT collection in dollars.
in hbars

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +- `batchSize`: The batch size of the minting process.
The amount of NFTs minted in a single on-chain transaction (defaults to 5)

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +- `batchSize`: The batch size of the minting process.
The amount of NFTs minted in a single on-chain transaction (defaults to 5)

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +## NFT SDK Estimate Mint Metadata In Dollars
NFT SDK Estimate minting cost In Dollars

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +# NFT SDK Estimate Mint Metadata In Hbar
NFT SDK Estimate minting cost In Hbar

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +# NFT SDK Estimate Mint Metadata In Hbar
should be a h2, so `##`

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +# NFT SDK Increase NFT Supply
##

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +- `batchSize`: The batch size of the minting process.
The amount of NFTs minted in a single on-chain transaction (defaults to 5)

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +The `getHolderAndDuration` method is used to get the holder and duration of an NFT. This method runs without instance of `HederaNFTSDK` class.
does it run without an instance of HederaNFTSDK?

2024-03-21 10:52 UTC, BartoszSolkaArianelabs commented on README.md
> +### Parameters
please mention that user need to pass either hbarAmount or (amount and denominatingTokenId)

2024-03-21 10:54 UTC, michalrozekariane commented on README.md
> +- **Package: [FeeFactory](#feefactory)**
Spaces missing?

2024-03-21 10:54 UTC, michalrozekariane commented on README.md
> +Each of NFtSDK function are methods in class `NFTSDK` which is a wrapper around the Hedera NFT API. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
maybe it will be better to write: `NFT SDK` instead of `NFtSDK`

2024-03-21 10:54 UTC, michalrozekariane commented on README.md
> +Create new instance of `NFTSDK` class by passing the operator account ID, operator private key, and network to the constructor.
new instance of `HederaNFTSDK` instead of `NFTSDK`

2024-03-21 10:54 UTC, michalrozekariane commented on README.md
> +- `network`: The network to use (mainnet or testnet or previewnet or localNode).
potential fix: `mainnet, testnet, previewnet or loocalNode`

2024-03-21 10:56 UTC, StanislawMazowieckiAriane commented on README.md
> +The `getHolderAndDuration` method is used to get the holder and duration of an NFT. This method runs without instance of `HederaNFTSDK` class.
yes

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +Each of NFtSDK function are methods in class `NFTSDK` which is a wrapper around the Hedera NFT API. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +Create new instance of `NFTSDK` class by passing the operator account ID, operator private key, and network to the constructor.
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +```
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +Method return number which is the estimated cost of creating a new NFT collection in dollars.
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +# NFT SDK Estimate Mint Metadata In Hbar
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +# NFT SDK Increase NFT Supply
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +- `batchSize`: The batch size of the minting process.
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +### Parameters
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +- **Package: [FeeFactory](#feefactory)**
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +Each of NFtSDK function are methods in class `NFTSDK` which is a wrapper around the Hedera NFT API. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +Create new instance of `NFTSDK` class by passing the operator account ID, operator private key, and network to the constructor.
Done

2024-03-21 14:58 UTC, StanislawMazowieckiAriane commented on README.md
> +- `network`: The network to use (mainnet or testnet or previewnet or localNode).
Done

2024-03-21 14:59 UTC, StanislawMazowieckiAriane commented on README.md
> +- `batchSize`: The batch size of the minting process.
Done

2024-03-21 14:59 UTC, StanislawMazowieckiAriane commented on README.md
> +- `batchSize`: The batch size of the minting process.
Done

2024-03-21 15:00 UTC, StanislawMazowieckiAriane commented on README.md
> +## NFT SDK Estimate Mint Metadata In Dollars
Done

2024-03-21 15:12 UTC, michalrozekariane approved these changes

2024-03-22 10:09 UTC, BartoszSolkaArianelabs requested changes

2024-03-22 10:09 UTC, BartoszSolkaArianelabs commented on README.md
> +Each of HederaNFTSDK function are methods in class `HederaNFTSDK` which is a wrapper around the Hedera HederaNFTSDK. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
`wrapper around the Hedera HederaNFTSDK` -> `wrapper around the native Hedera SDK`

2024-03-22 10:09 UTC, BartoszSolkaArianelabs commented on README.md
> +Method return number which is the estimated cost of creating a new NFT collection in Hbars.
This should be dollars.

The one after (line 802) should say Hbars

2024-03-22 10:35 UTC, StanislawMazowieckiAriane commented on README.md
> +Each of HederaNFTSDK function are methods in class `HederaNFTSDK` which is a wrapper around the Hedera HederaNFTSDK. The class is used to create a new NFT collection, mint NFTs, and transfer NFTs.
Done

2024-03-22 10:35 UTC, StanislawMazowieckiAriane commented on README.md
> +Method return number which is the estimated cost of creating a new NFT collection in Hbars.
Done

2024-03-22 11:59 UTC, BartoszSolkaArianelabs approved these changes

2024-03-22 14:58 UTC, merged