Feat: Add createToken estimation
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #6
Opened 2024-02-14 13:07 UTC by StanislawMazowieckiAriane

#3

2024-02-15 10:59 UTC, se7enarianelabs requested changes

2024-02-15 10:59 UTC, se7enarianelabs commented on src/helpers/get-string-size.ts
> +};
why not str.length?

2024-02-15 10:59 UTC, se7enarianelabs commented on src/nftSDKFunctions/index.ts
> +    customFees?: CustomFixedFee[] | CustomRoyaltyFee[];
custom fees should be a list of CustomFees(it can include simultaneous Fixed and RoyaltyFees)

2024-02-15 10:59 UTC, se7enarianelabs commented on src/helpers/calculatePrice.ts
> +        if (usage[validFeeComponent][usageItem] === undefined) {
what if it's null?

2024-02-15 10:59 UTC, se7enarianelabs commented on src/helpers/calculatePrice.ts
> +      for (const subKey of ['constant', 'bpt', 'vpt', 'rbh', 'sbh', 'gas', 'bpr', 'sbpr', 'min', 'max'] as UsageKeys[]) {
['constant', 'bpt', 'vpt', 'rbh', 'sbh', 'gas', 'bpr', 'sbpr', 'min', 'max'] extract this to a variable

2024-02-15 10:59 UTC, se7enarianelabs commented on src/helpers/calculatePrice.ts
> +    for (const component of ['node', 'network', 'service'] as UsageComponents[]) {
extract this to a variable: ['node', 'network', 'service']

2024-02-15 10:59 UTC, se7enarianelabs commented on src/helpers/get-token-create-with-fees-usage.ts
> +  customFees?: CustomFixedFee[] | CustomRoyaltyFee[];
it can be a array of both

2024-02-15 10:59 UTC, se7enarianelabs commented on src/nftSDKFunctions/estimate-create-collection-in-dollars.ts
> +}: EstimateCreateCollectionType) => {
What with the memo field?
https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/define-a-token

2024-02-15 10:59 UTC, se7enarianelabs commented on src/nftSDKFunctions/estimate-create-collection-in-dollars.ts
> +  }
This can be extracted to a seperate function

2024-02-15 10:59 UTC, se7enarianelabs commented on src/nftSDKFunctions/estimate-create-collection-in-dollars.ts
> +    return usage ? FeeTool.getCreateTokenWithFeesCost(usage) : 0;
In which scenario 0 will be returned?

2024-02-15 10:59 UTC, se7enarianelabs commented on src/nftSDKFunctions/estimate-create-collection-in-dollars.ts
> +  return tokenUsage ? FeeTool.getCreateTokenCost(tokenUsage) : 0;
When tokenUsage will be falsy?

2024-02-15 10:59 UTC, se7enarianelabs commented on src/nftSDKFunctions/index.ts
> +    customFees?: CustomFixedFee[] | CustomRoyaltyFee[];
customFees can be an array of Fixed and Royalty fees

2024-02-15 12:23 UTC, StanislawMazowieckiAriane commented on src/helpers/get-string-size.ts
> +};
The str.length property in JavaScript returns the number of 16-bit code units in a string, which is not always the same as the number of characters, especially if the string contains non-BMP characters (those that require more than 16 bits to represent, like many emoji).  

On the other hand, the Blob.size property returns the number of bytes, which can be more accurate for measuring the size of a string in bytes, especially if the string contains multi-byte characters.

2024-02-15 12:23 UTC, StanislawMazowieckiAriane commented on src/nftSDKFunctions/index.ts
> +    customFees?: CustomFixedFee[] | CustomRoyaltyFee[];
Done. I have added a new test in the fee factory for this

2024-02-15 12:24 UTC, StanislawMazowieckiAriane commented on src/helpers/calculatePrice.ts
> +        if (usage[validFeeComponent][usageItem] === undefined) {
Done

2024-02-15 12:24 UTC, StanislawMazowieckiAriane commented on src/utils/constants/fee-tool-config.ts
> +};
Estimate calculation from mintbox

2024-02-15 12:25 UTC, StanislawMazowieckiAriane commented on src/utils/constants/fee-tool-config.ts
> +  feeSchedules: FEE_SCHEDULES.CREATE_TOKEN_NON_FUNGIBLE_UNIQUE_WITH_CUSTOM_FEES,
Estimate calculation from mintbox

2024-02-15 12:27 UTC, StanislawMazowieckiAriane commented on src/helpers/calculatePrice.ts
> +      for (const subKey of ['constant', 'bpt', 'vpt', 'rbh', 'sbh', 'gas', 'bpr', 'sbpr', 'min', 'max'] as UsageKeys[]) {
Estimate calculation from mintbox

2024-02-15 12:27 UTC, BartoszSolkaArianelabs commented on src/nftSDKFunctions/token-create-usage.ts
> +    memoSize: getStringSize(''),
let's talk about this and `isAutoRenewAccountSet` on our next planning meeting

2024-02-15 14:08 UTC, se7enarianelabs requested changes

2024-02-15 14:08 UTC, se7enarianelabs commented on src/nftSDKFunctions/index.ts
> +    mirrorNodeUrl,
Why don't you save the mirrorNodeUrl as well in the object similar to network?

2024-02-15 15:19 UTC, StanislawMazowieckiAriane commented on src/helpers/calculatePrice.ts
> +/*-
Done

2024-02-15 15:24 UTC, StanislawMazowieckiAriane commented on src/nftSDKFunctions/index.ts
> +    mirrorNodeUrl,
Done

2024-02-16 09:02 UTC, BartoszSolkaArianelabs approved these changes

2024-02-16 09:26 UTC, michalrozekariane approved these changes

2024-02-16 09:40 UTC, se7enarianelabs requested changes

2024-02-16 09:40 UTC, se7enarianelabs commented on src/helpers/calculate-price.ts
> +        if (usage[validFeeComponent][usageItem] === undefined) {
what if it's null?

2024-02-19 08:48 UTC, StanislawMazowieckiAriane commented on src/helpers/calculate-price.ts
> +        if (usage[validFeeComponent][usageItem] === undefined) {
Done

2024-02-19 08:56 UTC, se7enarianelabs approved these changes

2024-02-19 09:15 UTC, merged