Feat: Refactor risk functions
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #61
Opened 2024-03-21 12:40 UTC by StanislawMazowieckiAriane

2024-03-21 15:10 UTC, michalrozekariane approved these changes

2024-03-22 14:03 UTC, BartoszSolkaArianelabs requested changes

2024-03-22 14:03 UTC, BartoszSolkaArianelabs commented on src/types/risk.ts
> +  supply_type?: 'INFINITE' | 'FINITE';
all factors should be numbers IMO.

This should be removed.

2024-03-25 08:41 UTC, StanislawMazowieckiAriane commented on src/types/risk.ts
> +  supply_type?: 'INFINITE' | 'FINITE';
Done

2024-03-25 08:43 UTC, BartoszSolkaArianelabs approved these changes

2024-03-25 10:10 UTC, norbert-kulus-arianelabs commented on src/risk/index.ts
>      riskLevel,
the type of ``riskLevel`` could be specifically ``'NORISK' | 'LOW' | 'MEDIUM' | 'HIGH'`` instead of just ``string``

2024-03-25 10:43 UTC, StanislawMazowieckiAriane commented on src/risk/index.ts
>      riskLevel,
Done

2024-03-25 14:05 UTC, merged