Feat: Add estimateNftMint function
Ashe-Oro-Accelerator/hedera-nft-utilities pull request #8
Opened 2024-02-15 11:33 UTC by StanislawMazowieckiAriane

#7

2024-02-15 11:48 UTC, BartoszSolkaArianelabs requested changes

2024-02-15 11:48 UTC, BartoszSolkaArianelabs commented on src/test/e2e/estimate-nft-minting-cost-function-e2e.test.ts
> +        expect((mintTokenReceipt.totalSupply.toString() * AVERAGE_COST_OF_MINT_1_AVERAGE_METADATA_JSON) / exchangeRateInDollars).toEqual(
it should check for the actual cost, not calculate it from a formula

2024-02-15 11:48 UTC, BartoszSolkaArianelabs commented on src/test/unit/estimate-nft-minting-cost-function.test.ts
> +    expect(result).toBe((5 * AVERAGE_COST_OF_MINT_1_AVERAGE_METADATA_JSON) / 10);
I would like the expected value to be a constant, not a calculation of a formula. Same for other tests

2024-02-15 11:48 UTC, BartoszSolkaArianelabs commented on src/nftSDKFunctions/estimate-nft-minting-cost-function.ts
> +export const estimateNftMintingCostFunction = async ({
Is this in Dollars or Hbar? I think it would be good to have it in name. BTW, shouldn't we have two functions? One for HBAR and another one for USD?

2024-02-15 12:41 UTC, BartoszSolkaArianelabs commented on src/test/e2e/estimate-nft-minting-cost-function-e2e.test.ts
> +
remember to close the nftSdk.client in each end2end test file. When not closed it results in

```
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

2024-02-15 15:50 UTC, StanislawMazowieckiAriane commented on src/test/unit/estimate-nft-minting-cost-function.test.ts
> +    expect(result).toBe((5 * AVERAGE_COST_OF_MINT_1_AVERAGE_METADATA_JSON) / 10);
Done

2024-02-15 15:50 UTC, StanislawMazowieckiAriane commented on src/test/e2e/estimate-nft-minting-cost-function-e2e.test.ts
> +        expect((mintTokenReceipt.totalSupply.toString() * AVERAGE_COST_OF_MINT_1_AVERAGE_METADATA_JSON) / exchangeRateInDollars).toEqual(
Done

2024-02-15 15:55 UTC, StanislawMazowieckiAriane commented on src/nftSDKFunctions/estimate-nft-minting-cost-function.ts
> +export const estimateNftMintingCostFunction = async ({
The task says only about hbars. Should there be also a dollar function?

2024-02-16 09:01 UTC, BartoszSolkaArianelabs commented on src/nftSDKFunctions/estimate-nft-minting-cost-function.ts
> +export const estimateNftMintingCostFunction = async ({
let's do both

2024-02-16 11:29 UTC, BartoszSolkaArianelabs approved these changes

2024-02-19 08:38 UTC, StanislawMazowieckiAriane commented on src/nftSDKFunctions/estimate-nft-minting-cost-function.ts
> +export const estimateNftMintingCostFunction = async ({
Done

2024-02-19 08:56 UTC, se7enarianelabs approved these changes

2024-02-19 09:22 UTC, merged